# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(choices=[('1', 'darty'), ('2', 'kelkoo'), ('3', 'boulanger'), ('4', 'pricerunner'), ('5', 'rueducommerce'), ('6', 'groupdigital')], default='1', max_length=6, verbose_name='Store ID')),
                ('country', models.CharField(choices=[('fr', 'France'), ('es', 'Spain')], default='fr', max_length=2, verbose_name='Country')),
                ('nombre', models.CharField(max_length=200, verbose_name='Store name')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
