# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaCompany',
            fields=[
                ('_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Name Company')),
                ('country', models.CharField(choices=[('fr', 'France'), ('es', 'Spain')], default='fr', max_length=2, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Company MA',
                'verbose_name_plural': 'Companies MA',
            },
        ),
    ]
