# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.CharField(choices=[('TV_000', 'Television'), ('COMPU_000', 'Laptop'), ('FRIGO_000', 'Refrigerador'), ('FRIGO_001', 'Refrigerador combinado'), ('FRIGO_002', 'Congelador'), ('FRIGO_003', 'Cava de vino'), ('TLF_000', 'Mobile')], default='TV_000', max_length=10, verbose_name='Category')),
                ('nombre', models.CharField(max_length=200)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', related_query_name='items', to='stores.Store')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
