# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGenerated',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=3000)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls_generated', related_query_name='urls_generated', to='tasks.Job')),
            ],
            options={
                'verbose_name': 'Url (Webcraping)',
                'verbose_name_plural': 'Urls (Webcraping)',
            },
        ),
    ]
