# Generated by Django 2.0 on 2018-03-21 15:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=6)),
                ('category_id', models.CharField(choices=[('TV_000', 'Television'), ('COMPU_000', 'Laptop'), ('FRIGO_000', 'Refrigerador'), ('FRIGO_001', 'Refrigerador combinado'), ('FRIGO_002', 'Congelador'), ('FRIGO_003', 'Cava de vino'), ('TLF_000', 'Mobile')], default='TV_000', max_length=10, verbose_name='Category')),
                ('nombre', models.CharField(max_length=200)),
                ('ficha_tecnica', django.contrib.postgres.fields.jsonb.JSONField()),
                ('detalles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tiendas', django.contrib.postgres.fields.jsonb.JSONField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_similar_results', related_query_name='substitution_similar_results', to='tasks.Job')),
            ],
            options={
                'verbose_name': 'Product (Webscraping)',
                'verbose_name_plural': 'Products (Webscraping)',
            },
        ),
    ]
