# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ma_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaProfile',
            fields=[
                ('_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('fr', 'French'), ('es', 'Spanish')], default='fr', max_length=2, verbose_name='Language')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ma_profiles', related_query_name='ma_profiles', to='ma_companies.MaCompany')),
            ],
            options={
                'verbose_name': 'User Profile MA',
                'verbose_name_plural': 'User Profiles MA',
            },
        ),
    ]
