# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaBrand',
            fields=[
                ('_ma_brand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_brand', models.CharField(blank=True, max_length=20, verbose_name='Brand Id')),
                ('name_brand', models.CharField(blank=True, max_length=100, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Item Brand',
                'verbose_name_plural': 'Item Brands',
            },
        ),
        migrations.CreateModel(
            name='MaItemType',
            fields=[
                ('_ma_item_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_item_type', models.CharField(blank=True, max_length=20, verbose_name='Item Type Id')),
                ('name_item_type', models.CharField(blank=True, max_length=100, verbose_name='Item Type Name')),
                ('brands', models.ManyToManyField(to='ma_items.MaBrand')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
            },
        ),
        migrations.CreateModel(
            name='MaModel',
            fields=[
                ('_ma_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_model', models.CharField(max_length=20, verbose_name='Model Id')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ma_models', related_query_name='ma_models', to='ma_items.MaBrand')),
            ],
            options={
                'verbose_name': 'Item Model',
                'verbose_name_plural': 'Item Models',
            },
        ),
        migrations.CreateModel(
            name='MaTempModel',
            fields=[
                ('_ma_temp_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_model', models.CharField(max_length=20, verbose_name='Model Id')),
                ('name_model', models.CharField(max_length=100, verbose_name='Model Name')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ma_temp_models', related_query_name='ma_temp_models', to='tasks.Job')),
            ],
            options={
                'verbose_name': 'Temporal Model',
                'verbose_name_plural': 'Temporal Models',
            },
        ),
    ]
